### ISSUE TITLE
Hi, this seems like a good idea, but...

### ISSUE THREAD

**Issue by cleesmith** [nifey/epub2sphinx#31]
Any help would be great, as I am a writer who likes to host my own ebooks and Vellum (vellum.pub) generates very 
nice epub files and would be an easy way to make static html files. Thanks.

I'm on a Mac in the terminal and after doing  the following and restarting:
1. brew install pandoc ... no errors
2. python3 setup.py install ... no errors

... but I get this error everytime:
...............................
iMac ~ % epub2sphinx --version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/epub2sphinx", line 33, in <module>
    sys.exit(load_entry_point('epub2sphinx==0.0.3', 'console_scripts', 'epub2sphinx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/epub2sphinx", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/epub2sphinx-0.0.3-py3.11.egg/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
...............................

iMac info:
Intel, Ventura 13.2.1

iMac ~ % brew -v
Homebrew 4.0.10

iMac ~ % python3 --version
Python 3.11.1

... other python github projects are working just fine, so what am I missing, thoughts?

**Comment by nifey** [comment]
Hello @cleesmith, 

It looks like the Click module is missing in your installation.
Try installing the click module and see if that fixes the issue:
`pip install click`

Another alternative is to install epub2sphinx directly using pip:
`pip install epub2sphinx`

I just updated the latest commits to the Python package index, so I would recommend uninstalling the older epub2sphinx and installing epub2sphinx using pip.
